version: '3.3'

services:
  db:
    image: postgres:13.10
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: fairfay/foodgram-backend:latest
    build: ../backend
    restart: always
    volumes:
      - backend_static:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: fairfay/foodgram-front:latest
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - ../frontend/build:/app/build/
    depends_on:
      - backend

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../frontend/build:/usr/share/nginx/html:ro
      - backend_static:/var/www/django_static:ro
      - media_value:/var/www/media:ro
    depends_on:
      - backend
      - frontend

volumes:
  backend_static:
  media_value:
  db_value: