version: '3.8'

services:
  db:
    image: postgres:13.10
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    # image: fairfay/foodgram-backend:latest
    build: ../backend
    restart: always
    volumes:
      - ../backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - ./.env
    depends_on:
      - db

  frontend:
    # image: fairfay/foodgram-front:latest
    container_name: foodgram-front
    build: ../frontend
    ports:
      - "3000:80"
    volumes:
      - ../frontend/build:/app/build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.25.4-alpine
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../frontend/build:/app/html
      - ../backend/static:/app/static
      - ../backend/media:/app/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static_volume:
  media_volume:
